language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# command to run tests
env:
  - PYTHONPATH="${PYTHONPATH}:Calculator:FileUtilities:Statistics:CsvReader:RandomGenerator"
script:
  - python -m  unittest discover -s  Tests

branches:
  only:
    - master